name: OWASP Dependency Check (dev)

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Dependency-Check using Docker
        run: |
          mkdir -p reports
          docker run --rm \
            -v "$(pwd)":/src \
            -v "$(pwd)/reports":/report \
            owasp/dependency-check:latest \
            --scan /src \
            --out /report \
            --format HTML \
            --project springboot-app

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: reports
